# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

default:
  tags:
    - io
    - shell-exec

stages:
  - dummy

dummy:
  stage: dummy
  script:
    - /bin/true # this stage do nothing but without it pipeline wont works
  when: manual

include:
  - project: 'continuous-delivery/ggw'
    ref: IO-6745_ci_pipelines
    file: '/gitlab-ci-sync-job.yml'
