# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: busybox:latest

default:
  tags:
    - io

stages:
  - sync
  - build
  - test
  - deploy

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"
  - env | sort

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

sync:
# GITHUBHOOK
# GITHUBHOOKREF
# GITHUBHOOKREFBEFORE
# GITHUBHOOKREFAFTER
  variables:
    GIT_STRATEGY: clone
  rules:
    - if: '$GITHUBHOOK == "true"'
      allow_failure: true
  image: alpine:git
  stage: sync
  script:
    - echo "$GITHUB_READONLY_KEY" > github.key
    - git fetch -f -t -P --all
    - GIT_SSH_COMMAND='ssh -i github.key -o IdentitiesOnly=yes' git remote add -f --tags --mirror=fetch github git@github.com:halvaborsch/my-mirror.git
    - git push -v --all origin
  after_script:
    - rm github.key

build1:
  stage: build
  script:
    - echo "Do your build here"

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
