# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

default:
  tags:
    - io
    - shell-exec

stages:
  - sync
  - build
  - test
  - deploy

before_script:
  - echo "Before script section"
  - echo "For example you might run an update here or install a build dependency"
  - echo "Or perhaps you might print out some debugging details"
  - env | sort

after_script:
  - echo "After script section"
  - echo "For example you might do some cleanup here"

sync:
# GITHUBHOOK
# GITHUBHOOKREF
# GITHUBHOOKREFBEFORE
# GITHUBHOOKREFAFTER
  variables:
    GIT_STRATEGY: clone
    GIT_SSH_COMMAND: ssh -i .github.key -o StrictHostKeyChecking=no -o IdentitiesOnly=yes
  rules:
    - if: '$GITHUBHOOK == "true"'
      allow_failure: true
  stage: sync
  script:
    - set -x
    - git fetch -f -t -P --all
      # check if current commit is already HEAD of the branch
    - if [[ "$( git rev-parse remotes/origin/${GITHUBREF} )" == "$( git rev-parse ${GITHUBREFAFTER})" ]]; then
        echo "Branch ${GITHUBREF} is up to date we'll skip the sync.";
        exit 0;
      fi
    - git remote add -f --tags github git@github.com:halvaborsch/my-mirror.git
      # check if current commit is one step away from remote
    - if [[ "$( git rev-parse remotes/origin/${GITHUBREF} )" == "$( git rev-parse ${GITHUBREFBEFORE})" ]]; then
        echo "Making clear push"; 
        git push -v --tags remotes/github/${GITHUBREF} remotes/origin/${GITHUBREF}
        exit $?;
      fi
      # check if local and github branches is on fast-forward line
    - if git merge-base --is-ancestor remotes/github/${GITHUBREF} remotes/origin/${GITHUBREF}; then
        git remote set-url --push origin ssh://git@${CI_SERVER_HOST}/${CI_PROJECT_PATH}
        git checkout remotes/origin/${GITHUBREF};
        git pull --ff-only --tags origin $( git rev-parse remotes/github/${GITHUBREF} );
        git push -v --progress --tags origin HEAD:${GITHUBREF};
      fi
  before_script:
    - echo "$GITHUB_READONLY_KEY" > .github.key 
    - chmod 0600 .github.key
  after_script:
    - sleep 60
    - rm .github.key

build1:
  stage: build
  script:
    - echo "Do your build here"

test1:
  stage: test
  script:
    - echo "Do a test here"
    - echo "For example run a test suite"

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - echo "For example run a lint test"

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
